"""
CommandLine:
    main.py --db PZ_MUGU_19 --eid 13 --verbthumb

Notes:
    http://stackoverflow.com/questions/8312725/how-to-create-executable-file-for-a-qt-application
    http://stackoverflow.com/questions/6783194/background-thread-with-qthread-in-pyqt
    For windows need at least these dlls:
        mingwm10.dll
        libgcc_s_dw2-1.dll
        QtCore4.dll
        QtGui4.dll

Error Notes:
[guitool.qtapp_loop()] starting qt app loop: qwin=<ibeis.gui.newgui.IBEISMainWindow object at 0x7f556abcab00>
[guitool] qapp.setActiveWindow(qwin)
[guitool.qtapp_loop()] qapp.exec_()  # runing main loop
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 108, in myexcepthook
    tbtext = ''.join(traceback.format_exception(type, value, tb))
  File "/usr/lib/python2.7/traceback.py", line 141, in format_exception
    list = list + format_tb(tb, limit)
  File "/usr/lib/python2.7/traceback.py", line 76, in format_tb
    return format_list(extract_tb(tb, limit))
  File "/usr/lib/python2.7/traceback.py", line 101, in extract_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/usr/lib/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
  File "/usr/lib/python2.7/linecache.py", line 40, in getlines
    return updatecache(filename, module_globals)
  File "/usr/lib/python2.7/linecache.py", line 132, in updatecache
    with open(fullname, 'rU') as fp:
RuntimeError: maximum recursion depth exceeded

Original exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 731, in index
    node = parent_node[row]
  File "/home/joncrall/code/guitool/guitool/api_tree_node.py", line 47, in __getitem__
    return self.get_child(index)
  File "/home/joncrall/code/guitool/guitool/api_tree_node.py", line 72, in get_child
    self.lazy_checks()
  File "/home/joncrall/code/guitool/guitool/api_tree_node.py", line 128, in lazy_checks
    if isinstance(self.child_nodes, GeneratorType):
RuntimeError: maximum recursion depth exceeded in __instancecheck__
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 108, in myexcepthook
    tbtext = ''.join(traceback.format_exception(type, value, tb))
  File "/usr/lib/python2.7/traceback.py", line 141, in format_exception
    list = list + format_tb(tb, limit)
  File "/usr/lib/python2.7/traceback.py", line 76, in format_tb
    return format_list(extract_tb(tb, limit))
  File "/usr/lib/python2.7/traceback.py", line 101, in extract_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/usr/lib/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
  File "/usr/lib/python2.7/linecache.py", line 40, in getlines
    return updatecache(filename, module_globals)
  File "/usr/lib/python2.7/linecache.py", line 132, in updatecache
    with open(fullname, 'rU') as fp:
RuntimeError: maximum recursion depth exceeded

---...
..
..

RuntimeError: maximum recursion depth exceeded
Error in APIThumbDelegate
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 109, in myexcepthook
    lexer = get_lexer_by_name('pytb', stripall=True)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 87, in get_lexer_by_name
    _load_lexers(module_name)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 41, in _load_lexers
    mod = __import__(module_name, None, None, ['__all__'])
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/python.py", line 14, in <module>
    from pygments.lexer import Lexer, RegexLexer, include, bygroups, using, \
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 20, in <module>
    from pygments.filters import get_filter_by_name
  File "/usr/local/lib/python2.7/dist-packages/pygments/filters/__init__.py", line 13, in <module>
    import re
RuntimeError: maximum recursion depth exceeded while calling a Python object

Original exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_thumb_delegate.py", line 324, in sizeHint
    utool.printex(ex, 'Error in APIThumbDelegate', tb=True)
  File "/home/joncrall/code/utool/utool/util_dbg.py", line 877, in printex
    exstr = formatex(ex, msg, prefix, key_list, locals_, iswarning, tb=tb)
  File "/home/joncrall/code/utool/utool/util_dbg.py", line 916, in formatex
    errstr_list.append(traceback.format_exc())
  File "/usr/lib/python2.7/traceback.py", line 242, in format_exc
    return ''.join(format_exception(etype, value, tb, limit))
  File "/usr/lib/python2.7/traceback.py", line 141, in format_exception
    list = list + format_tb(tb, limit)
  File "/usr/lib/python2.7/traceback.py", line 76, in format_tb
    return format_list(extract_tb(tb, limit))
  File "/usr/lib/python2.7/traceback.py", line 101, in extract_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/usr/lib/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
  File "/usr/lib/python2.7/linecache.py", line 40, in getlines
    return updatecache(filename, module_globals)
RuntimeError: maximum recursion depth exceeded
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 109, in myexcepthook
    lexer = get_lexer_by_name('pytb', stripall=True)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 87, in get_lexer_by_name
    _load_lexers(module_name)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 41, in _load_lexers
    mod = __import__(module_name, None, None, ['__all__'])
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/python.py", line 14, in <module>
    from pygments.lexer import Lexer, RegexLexer, include, bygroups, using, \
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 20, in <module>
    from pygments.filters import get_filter_by_name
  File "/usr/local/lib/python2.7/dist-packages/pygments/filters/__init__.py", line 13, in <module>
    import re
RuntimeError: maximum recursion depth exceeded while calling a Python object

Original exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 832, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 621, in _get_data
    utool.printex(ex, 'problem getting in column %r' % (col,))
  File "/home/joncrall/code/utool/utool/util_dbg.py", line 887, in printex
    print_func('\n+------\n')
  File "/home/joncrall/code/utool/utool/util_inject.py", line 144, in print
    util_logging.__UTOOL_PRINT__(*args)
  File "/home/joncrall/code/utool/utool/util_logging.py", line 225, in utool_print
    return  __UTOOL_ROOT_LOGGER__.info(', '.join(map(str, args)))
  File "/usr/lib/python2.7/logging/__init__.py", line 1151, in info
    if self.isEnabledFor(INFO):
  File "/usr/lib/python2.7/logging/__init__.py", line 1351, in isEnabledFor
    return level >= self.getEffectiveLevel()
RuntimeError: maximum recursion depth exceeded
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 109, in myexcepthook
    lexer = get_lexer_by_name('pytb', stripall=True)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 87, in get_lexer_by_name
    _load_lexers(module_name)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 41, in _load_lexers
    mod = __import__(module_name, None, None, ['__all__'])
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/python.py", line 14, in <module>
    from pygments.lexer import Lexer, RegexLexer, include, bygroups, using, \
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 20, in <module>
    from pygments.filters import get_filter_by_name
  File "/usr/local/lib/python2.7/dist-packages/pygments/filters/__init__.py", line 13, in <module>
    import re
RuntimeError: maximum recursion depth exceeded while calling a Python object

Original exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 813, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 621, in _get_data
    utool.printex(ex, 'problem getting in column %r' % (col,))
  File "/home/joncrall/code/utool/utool/util_dbg.py", line 887, in printex
    print_func('\n+------\n')
  File "/home/joncrall/code/utool/utool/util_inject.py", line 144, in print
    util_logging.__UTOOL_PRINT__(*args)
  File "/home/joncrall/code/utool/utool/util_logging.py", line 225, in utool_print
    return  __UTOOL_ROOT_LOGGER__.info(', '.join(map(str, args)))
  File "/usr/lib/python2.7/logging/__init__.py", line 1152, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1270, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/logging/__init__.py", line 1244, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
  File "/usr/lib/python2.7/logging/__init__.py", line 266, in __init__
    self.levelname = getLevelName(level)
RuntimeError: maximum recursion depth exceeded
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 109, in myexcepthook
    lexer = get_lexer_by_name('pytb', stripall=True)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 87, in get_lexer_by_name
    _load_lexers(module_name)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 41, in _load_lexers
    mod = __import__(module_name, None, None, ['__all__'])
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/python.py", line 14, in <module>
    from pygments.lexer import Lexer, RegexLexer, include, bygroups, using, \
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 24, in <module>
    from pygments.regexopt import regex_opt
  File "/usr/local/lib/python2.7/dist-packages/pygments/regexopt.py", line 19, in <module>
    CS_ESCAPE = re.compile(r'[\^\\\-\]]')
  File "/usr/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 242, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python2.7/sre_compile.py", line 498, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python2.7/sre_parse.py", line 678, in parse
    source = Tokenizer(str)
  File "/usr/lib/python2.7/sre_parse.py", line 181, in __init__
    self.__next()
RuntimeError: maximum recursion depth exceeded
Original exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 845, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 621, in _get_data
    utool.printex(ex, 'problem getting in column %r' % (col,))
  File "/home/joncrall/code/utool/utool/util_dbg.py", line 887, in printex
    print_func('\n+------\n')
  File "/home/joncrall/code/utool/utool/util_inject.py", line 144, in print
    util_logging.__UTOOL_PRINT__(*args)
  File "/home/joncrall/code/utool/utool/util_logging.py", line 225, in utool_print
    return  __UTOOL_ROOT_LOGGER__.info(', '.join(map(str, args)))
  File "/usr/lib/python2.7/logging/__init__.py", line 1152, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1270, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/logging/__init__.py", line 1244, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
  File "/usr/lib/python2.7/logging/__init__.py", line 266, in __init__
    self.levelname = getLevelName(level)
RuntimeError: maximum recursion depth exceeded
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 109, in myexcepthook
    lexer = get_lexer_by_name('pytb', stripall=True)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 87, in get_lexer_by_name
    _load_lexers(module_name)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 41, in _load_lexers
    mod = __import__(module_name, None, None, ['__all__'])
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/python.py", line 14, in <module>
    from pygments.lexer import Lexer, RegexLexer, include, bygroups, using, \
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 24, in <module>
    from pygments.regexopt import regex_opt
  File "/usr/local/lib/python2.7/dist-packages/pygments/regexopt.py", line 19, in <module>
    CS_ESCAPE = re.compile(r'[\^\\\-\]]')
  File "/usr/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 242, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python2.7/sre_compile.py", line 498, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python2.7/sre_parse.py", line 678, in parse
    source = Tokenizer(str)
  File "/usr/lib/python2.7/sre_parse.py", line 181, in __init__
    self.__next()
RuntimeError: maximum recursion depth exceeded

Original exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 845, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 621, in _get_data
    utool.printex(ex, 'problem getting in column %r' % (col,))
  File "/home/joncrall/code/utool/utool/util_dbg.py", line 887, in printex
    print_func('\n+------\n')
  File "/home/joncrall/code/utool/utool/util_inject.py", line 144, in print
    util_logging.__UTOOL_PRINT__(*args)
  File "/home/joncrall/code/utool/utool/util_logging.py", line 225, in utool_print
    return  __UTOOL_ROOT_LOGGER__.info(', '.join(map(str, args)))
  File "/usr/lib/python2.7/logging/__init__.py", line 1152, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1270, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/logging/__init__.py", line 1244, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
  File "/usr/lib/python2.7/logging/__init__.py", line 266, in __init__
    self.levelname = getLevelName(level)
RuntimeError: maximum recursion depth exceeded
Error in APIThumbDelegate
Traceback (most recent call last):
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 109, in myexcepthook
    lexer = get_lexer_by_name('pytb', stripall=True)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 88, in get_lexer_by_name
    return _lexer_cache[name](**options)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 581, in __call__
    cls._tokens = cls.process_tokendef('', cls.get_tokendefs())
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 520, in process_tokendef
    cls._process_state(tokendefs, processed, state)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 502, in _process_state
    (tdef[0], state, cls, err))
ValueError: uncompilable regex '^(?=  File "[^"]+", line \\d+)' in state 'root' of <class 'pygments.lexers.python.PythonTracebackLexer'>: maximum recursion depth exceeded while calling a Python object

Original exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_thumb_delegate.py", line 324, in sizeHint
    utool.printex(ex, 'Error in APIThumbDelegate', tb=True)
  File "/home/joncrall/code/utool/utool/util_dbg.py", line 887, in printex
    print_func('\n+------\n')
  File "/home/joncrall/code/utool/utool/util_inject.py", line 144, in print
    util_logging.__UTOOL_PRINT__(*args)
  File "/home/joncrall/code/utool/utool/util_logging.py", line 225, in utool_print
    return  __UTOOL_ROOT_LOGGER__.info(', '.join(map(str, args)))
  File "/usr/lib/python2.7/logging/__init__.py", line 1152, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 942, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 879, in emit
    self.handleError(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 802, in handleError
    None, sys.stderr)
  File "/usr/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python2.7/traceback.py", line 67, in print_tb
    '  File "%s", line %d, in %s' % (filename, lineno, name))
RuntimeError: maximum recursion depth exceeded
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 109, in myexcepthook
    lexer = get_lexer_by_name('pytb', stripall=True)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 88, in get_lexer_by_name
    return _lexer_cache[name](**options)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 581, in __call__
    cls._tokens = cls.process_tokendef('', cls.get_tokendefs())
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 520, in process_tokendef
    cls._process_state(tokendefs, processed, state)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 502, in _process_state
    (tdef[0], state, cls, err))
ValueError: uncompilable regex '^(?=  File "[^"]+", line \\d+)' in state 'root' of <class 'pygments.lexers.python.PythonTracebackLexer'>: maximum recursion depth exceeded while calling a Python object

riginal exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 813, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 621, in _get_data
    utool.printex(ex, 'problem getting in column %r' % (col,))
  File "/home/joncrall/code/utool/utool/util_dbg.py", line 887, in printex
    print_func('\n+------\n')
  File "/home/joncrall/code/utool/utool/util_inject.py", line 144, in print
    util_logging.__UTOOL_PRINT__(*args)
  File "/home/joncrall/code/utool/utool/util_logging.py", line 225, in utool_print
    return  __UTOOL_ROOT_LOGGER__.info(', '.join(map(str, args)))
  File "/usr/lib/python2.7/logging/__init__.py", line 1152, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 942, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 879, in emit
    self.handleError(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 802, in handleError
    None, sys.stderr)
  File "/usr/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python2.7/traceback.py", line 68, in print_tb
    linecache.checkcache(filename)
  File "/usr/lib/python2.7/linecache.py", line 64, in checkcache
    if size != stat.st_size or mtime != stat.st_mtime:
RuntimeError: maximum recursion depth exceeded in cmp
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 109, in myexcepthook
    lexer = get_lexer_by_name('pytb', stripall=True)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 88, in get_lexer_by_name
    return _lexer_cache[name](**options)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 581, in __call__
    cls._tokens = cls.process_tokendef('', cls.get_tokendefs())
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 520, in process_tokendef
    cls._process_state(tokendefs, processed, state)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 502, in _process_state
    (tdef[0], state, cls, err))
ValueError: uncompilable regex '^(?=  File "[^"]+", line \\d+)' in state 'root' of <class 'pygments.lexers.python.PythonTracebackLexer'>: maximum recursion depth exceeded while calling a Python object

Original exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 845, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 621, in _get_data
    utool.printex(ex, 'problem getting in column %r' % (col,))
  File "/home/joncrall/code/utool/utool/util_dbg.py", line 887, in printex
    print_func('\n+------\n')
  File "/home/joncrall/code/utool/utool/util_inject.py", line 144, in print
    util_logging.__UTOOL_PRINT__(*args)
  File "/home/joncrall/code/utool/utool/util_logging.py", line 225, in utool_print
    return  __UTOOL_ROOT_LOGGER__.info(', '.join(map(str, args)))
  File "/usr/lib/python2.7/logging/__init__.py", line 1152, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 942, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 879, in emit
    self.handleError(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 802, in handleError
    None, sys.stderr)
  File "/usr/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python2.7/traceback.py", line 68, in print_tb
    linecache.checkcache(filename)
  File "/usr/lib/python2.7/linecache.py", line 64, in checkcache
    if size != stat.st_size or mtime != stat.st_mtime:
RuntimeError: maximum recursion depth exceeded in cmp
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 109, in myexcepthook
    lexer = get_lexer_by_name('pytb', stripall=True)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 88, in get_lexer_by_name
    return _lexer_cache[name](**options)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 581, in __call__
    cls._tokens = cls.process_tokendef('', cls.get_tokendefs())
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 520, in process_tokendef
    cls._process_state(tokendefs, processed, state)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 502, in _process_state
    (tdef[0], state, cls, err))
ValueError: uncompilable regex '^(?=  File "[^"]+", line \\d+)' in state 'root' of <class 'pygments.lexers.python.PythonTracebackLexer'>: maximum recursion depth exceeded while calling a Python object

Original exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 845, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 621, in _get_data
    utool.printex(ex, 'problem getting in column %r' % (col,))
  File "/home/joncrall/code/utool/utool/util_dbg.py", line 887, in printex
    print_func('\n+------\n')
  File "/home/joncrall/code/utool/utool/util_inject.py", line 144, in print
    util_logging.__UTOOL_PRINT__(*args)
  File "/home/joncrall/code/utool/utool/util_logging.py", line 225, in utool_print
    return  __UTOOL_ROOT_LOGGER__.info(', '.join(map(str, args)))
  File "/usr/lib/python2.7/logging/__init__.py", line 1152, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 942, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 879, in emit
    self.handleError(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 802, in handleError
    None, sys.stderr)
  File "/usr/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python2.7/traceback.py", line 68, in print_tb
    linecache.checkcache(filename)
  File "/usr/lib/python2.7/linecache.py", line 64, in checkcache
    if size != stat.st_size or mtime != stat.st_mtime:
RuntimeError: maximum recursion depth exceeded in cmp
Traceback (most recent call last):
Error in APIThumbDelegate

+------

<!!! EXCEPTION !!!>
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_thumb_delegate.py", line 314, in sizeHint
    thumb_path = dgt.get_thumb_path_if_exists(view, offset, qtindex)
  File "/home/joncrall/code/guitool/guitool/api_thumb_delegate.py", line 201, in get_thumb_path_if_exists
    data = dgt.get_model_data(qtindex)
  File "/home/joncrall/code/guitool/guitool/api_thumb_delegate.py", line 172, in get_model_data
    data = model.data(qtindex, QtCore.Qt.DisplayRole, **datakw)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 840, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 621, in _get_data
    utool.printex(ex, 'problem getting in column %r' % (col,))
  File "/home/joncrall/code/utool/utool/util_dbg.py", line 887, in printex
    print_func('\n+------\n')
  File "/home/joncrall/code/utool/utool/util_inject.py", line 144, in print
    util_logging.__UTOOL_PRINT__(*args)
  File "/home/joncrall/code/utool/utool/util_logging.py", line 225, in utool_print
    return  __UTOOL_ROOT_LOGGER__.info(', '.join(map(str, args)))
  File "/usr/lib/python2.7/logging/__init__.py", line 1152, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 942, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 879, in emit
    self.handleError(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 802, in handleError
    None, sys.stderr)
  File "/usr/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python2.7/traceback.py", line 67, in print_tb
    '  File "%s", line %d, in %s' % (filename, lineno, name))
RuntimeError: maximum recursion depth exceeded

[!sizeHint] Error in APIThumbDelegate
<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded
</!!! EXCEPTION !!!>

L______


+------

<!!! EXCEPTION !!!>
[!_get_data] problem getting in column 4
<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded
</!!! EXCEPTION !!!>

L______

Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 111, in myexcepthook
    formatted_text = highlight(tbtext, lexer, formatter)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 86, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 66, in format
    formatter.format(tokens, realoutfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 100, in format
    return Formatter.format(self, tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 136, in format_unencoded
    for ttype, value in tokensource:
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 192, in streamer
    for i, t, v in self.get_tokens_unprocessed(text):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 635, in get_tokens_unprocessed
    for item in action(self, m):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 324, in callback
    data), ctx):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 380, in callback
    lx = _other(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 581, in __call__
    cls._tokens = cls.process_tokendef('', cls.get_tokendefs())
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 520, in process_tokendef
    cls._process_state(tokendefs, processed, state)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 502, in _process_state
    (tdef[0], state, cls, err))
ValueError: uncompilable regex "'''" in state 'tsqs' of <class 'pygments.lexers.python.PythonLexer'>: maximum recursion depth exceeded while calling a Python object

Original exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 832, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 619, in _get_data
    data = getter(row_id, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_annot_funcs.py", line 579, in get_annot_exemplar_flags
    annot_exemplar_flag_list = ibs.db.get(const.ANNOTATION_TABLE, ('annot_exemplar_flag',), aid_list)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 449, in get
    return db.get_where(tblname, colnames, params_iter, where_clause, eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 420, in get_where
    eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 560, in _executemany_operation_fmt
    auto_commit=True, eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 994, in executemany
    with SQLExecutionContext(db, operation, **contextkw) as context:
  File "/home/joncrall/code/ibeis/ibeis/control/_sql_helpers.py", line 315, in __init__
    context.operation_type = get_operation_type(operation)  # Parse the optype
RuntimeError: maximum recursion depth exceeded

+------

<!!! EXCEPTION !!!>
[!_get_data] problem getting in column 4
<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded
</!!! EXCEPTION !!!>

L______

Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 111, in myexcepthook
    formatted_text = highlight(tbtext, lexer, formatter)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 86, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 66, in format
    formatter.format(tokens, realoutfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 100, in format
    return Formatter.format(self, tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 136, in format_unencoded
    for ttype, value in tokensource:
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 192, in streamer
    for i, t, v in self.get_tokens_unprocessed(text):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 635, in get_tokens_unprocessed
    for item in action(self, m):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 324, in callback
    data), ctx):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 380, in callback
    lx = _other(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 581, in __call__
    cls._tokens = cls.process_tokendef('', cls.get_tokendefs())
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 520, in process_tokendef
    cls._process_state(tokendefs, processed, state)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 502, in _process_state
    (tdef[0], state, cls, err))
ValueError: uncompilable regex "'''" in state 'tsqs' of <class 'pygments.lexers.python.PythonLexer'>: maximum recursion depth exceeded while calling a Python object

Original exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 845, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 619, in _get_data
    data = getter(row_id, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_annot_funcs.py", line 579, in get_annot_exemplar_flags
    annot_exemplar_flag_list = ibs.db.get(const.ANNOTATION_TABLE, ('annot_exemplar_flag',), aid_list)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 449, in get
    return db.get_where(tblname, colnames, params_iter, where_clause, eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 420, in get_where
    eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 560, in _executemany_operation_fmt
    auto_commit=True, eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 994, in executemany
    with SQLExecutionContext(db, operation, **contextkw) as context:
  File "/home/joncrall/code/ibeis/ibeis/control/_sql_helpers.py", line 315, in __init__
    context.operation_type = get_operation_type(operation)  # Parse the optype
RuntimeError: maximum recursion depth exceeded

+------

<!!! EXCEPTION !!!>
[!_get_data] problem getting in column 4
<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded
</!!! EXCEPTION !!!>

L______

Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 111, in myexcepthook
    formatted_text = highlight(tbtext, lexer, formatter)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 86, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 66, in format
    formatter.format(tokens, realoutfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 100, in format
    return Formatter.format(self, tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 136, in format_unencoded
    for ttype, value in tokensource:
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 192, in streamer
    for i, t, v in self.get_tokens_unprocessed(text):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 635, in get_tokens_unprocessed
    for item in action(self, m):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 324, in callback
    data), ctx):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 380, in callback
    lx = _other(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 581, in __call__
    cls._tokens = cls.process_tokendef('', cls.get_tokendefs())
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 520, in process_tokendef
    cls._process_state(tokendefs, processed, state)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 502, in _process_state
    (tdef[0], state, cls, err))
ValueError: uncompilable regex "'''" in state 'tsqs' of <class 'pygments.lexers.python.PythonLexer'>: maximum recursion depth exceeded while calling a Python object

Original exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 813, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 619, in _get_data
    data = getter(row_id, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_annot_funcs.py", line 579, in get_annot_exemplar_flags
    annot_exemplar_flag_list = ibs.db.get(const.ANNOTATION_TABLE, ('annot_exemplar_flag',), aid_list)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 449, in get
    return db.get_where(tblname, colnames, params_iter, where_clause, eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 420, in get_where
    eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 560, in _executemany_operation_fmt
    auto_commit=True, eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 994, in executemany
    with SQLExecutionContext(db, operation, **contextkw) as context:
  File "/home/joncrall/code/ibeis/ibeis/control/_sql_helpers.py", line 315, in __init__
    context.operation_type = get_operation_type(operation)  # Parse the optype
RuntimeError: maximum recursion depth exceeded

+------

<!!! EXCEPTION !!!>
[!_get_data] problem getting in column 5
<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded
</!!! EXCEPTION !!!>

L______

Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 111, in myexcepthook
    formatted_text = highlight(tbtext, lexer, formatter)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 86, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 66, in format
    formatter.format(tokens, realoutfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 100, in format
    return Formatter.format(self, tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 136, in format_unencoded
    for ttype, value in tokensource:
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 192, in streamer
    for i, t, v in self.get_tokens_unprocessed(text):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 635, in get_tokens_unprocessed
    for item in action(self, m):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 324, in callback
    data), ctx):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 380, in callback
    lx = _other(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 581, in __call__
    cls._tokens = cls.process_tokendef('', cls.get_tokendefs())
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 520, in process_tokendef
    cls._process_state(tokendefs, processed, state)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 502, in _process_state
    (tdef[0], state, cls, err))
ValueError: uncompilable regex "'''" in state 'tsqs' of <class 'pygments.lexers.python.PythonLexer'>: maximum recursion depth exceeded while calling a Python object

Original exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 845, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 619, in _get_data
    data = getter(row_id, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_annot_funcs.py", line 1799, in get_annot_yaw_texts
    yaw_list = ibs.get_annot_yaws(aid_list)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_annot_funcs.py", line 993, in get_annot_yaws
    yaw_list = ibs.db.get(const.ANNOTATION_TABLE, (ANNOT_YAW,), aid_list)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 449, in get
    return db.get_where(tblname, colnames, params_iter, where_clause, eager=eager, **kwargs)
RuntimeError: maximum recursion depth exceeded

+------

<!!! EXCEPTION !!!>
[!_get_data] problem getting in column 6
<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded
</!!! EXCEPTION !!!>

L______

Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 111, in myexcepthook
    formatted_text = highlight(tbtext, lexer, formatter)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 86, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 66, in format
    formatter.format(tokens, realoutfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 100, in format
    return Formatter.format(self, tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 136, in format_unencoded
    for ttype, value in tokensource:
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 192, in streamer
    for i, t, v in self.get_tokens_unprocessed(text):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 635, in get_tokens_unprocessed
    for item in action(self, m):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 324, in callback
    data), ctx):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 380, in callback
    lx = _other(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 581, in __call__
    cls._tokens = cls.process_tokendef('', cls.get_tokendefs())
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 520, in process_tokendef
    cls._process_state(tokendefs, processed, state)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 502, in _process_state
    (tdef[0], state, cls, err))
ValueError: uncompilable regex "'''" in state 'tsqs' of <class 'pygments.lexers.python.PythonLexer'>: maximum recursion depth exceeded while calling a Python object

Original exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 845, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 619, in _get_data
    data = getter(row_id, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_annot_funcs.py", line 1783, in get_annot_quality_texts
    quality_list = ibs.get_annot_qualities(aid_list)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_annot_funcs.py", line 1752, in get_annot_qualities
    const.ANNOTATION_TABLE, colnames, id_iter, id_colname='rowid', eager=eager)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 449, in get
    return db.get_where(tblname, colnames, params_iter, where_clause, eager=eager, **kwargs)
RuntimeError: maximum recursion depth exceeded

+------

<!!! EXCEPTION !!!>
[!_get_data] problem getting in column 2
<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded while getting the str of an object
</!!! EXCEPTION !!!>

L______

Error in APIThumbDelegate

+------

<!!! EXCEPTION !!!>
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_thumb_delegate.py", line 314, in sizeHint
    thumb_path = dgt.get_thumb_path_if_exists(view, offset, qtindex)
  File "/home/joncrall/code/guitool/guitool/api_thumb_delegate.py", line 201, in get_thumb_path_if_exists
    data = dgt.get_model_data(qtindex)
  File "/home/joncrall/code/guitool/guitool/api_thumb_delegate.py", line 172, in get_model_data
    data = model.data(qtindex, QtCore.Qt.DisplayRole, **datakw)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 840, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 619, in _get_data
    data = getter(row_id, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_chip_funcs.py", line 260, in get_annot_chip_thumbtup
    thumb_gpaths = ibs.get_annot_chip_thumbpath(aid_list, thumbsize=thumbsize,
  File "/home/joncrall/code/ibeis/ibeis/control/manual_chip_funcs.py", line 220, in get_annot_chip_thumbpath
    thumb_suffix = '_' + str(thumbsize) + const.CHIP_THUMB_SUFFIX
RuntimeError: maximum recursion depth exceeded while getting the str of an object

[!sizeHint] Error in APIThumbDelegate
<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded while getting the str of an object
</!!! EXCEPTION !!!>

L______


+------

<!!! EXCEPTION !!!>
[!_get_data] problem getting in column 5
<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded while calling a Python object
</!!! EXCEPTION !!!>

L______

Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 111, in myexcepthook
    formatted_text = highlight(tbtext, lexer, formatter)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 86, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 66, in format
    formatter.format(tokens, realoutfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 100, in format
    return Formatter.format(self, tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 136, in format_unencoded
    for ttype, value in tokensource:
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 192, in streamer
    for i, t, v in self.get_tokens_unprocessed(text):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 635, in get_tokens_unprocessed
    for item in action(self, m):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 324, in callback
    data), ctx):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 380, in callback
    lx = _other(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 581, in __call__
    cls._tokens = cls.process_tokendef('', cls.get_tokendefs())
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 520, in process_tokendef
    cls._process_state(tokendefs, processed, state)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 502, in _process_state
    (tdef[0], state, cls, err))
ValueError: uncompilable regex "'''" in state 'tsqs' of <class 'pygments.lexers.python.PythonLexer'>: maximum recursion depth exceeded in cmp

Original exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 845, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 619, in _get_data
    data = getter(row_id, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_annot_funcs.py", line 1799, in get_annot_yaw_texts
    yaw_list = ibs.get_annot_yaws(aid_list)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_annot_funcs.py", line 993, in get_annot_yaws
    yaw_list = ibs.db.get(const.ANNOTATION_TABLE, (ANNOT_YAW,), aid_list)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 449, in get
    return db.get_where(tblname, colnames, params_iter, where_clause, eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 420, in get_where
    eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 560, in _executemany_operation_fmt
    auto_commit=True, eager=eager, **kwargs)
RuntimeError: maximum recursion depth exceeded while calling a Python object

+------

<!!! EXCEPTION !!!>
[!_get_data] problem getting in column 6
<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded while calling a Python object
</!!! EXCEPTION !!!>

L______

Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 111, in myexcepthook
    formatted_text = highlight(tbtext, lexer, formatter)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 86, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 66, in format
    formatter.format(tokens, realoutfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 100, in format
    return Formatter.format(self, tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 136, in format_unencoded
    for ttype, value in tokensource:
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 192, in streamer
    for i, t, v in self.get_tokens_unprocessed(text):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 635, in get_tokens_unprocessed
    for item in action(self, m):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 324, in callback
    data), ctx):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 380, in callback
    lx = _other(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 581, in __call__
    cls._tokens = cls.process_tokendef('', cls.get_tokendefs())
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 520, in process_tokendef
    cls._process_state(tokendefs, processed, state)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 502, in _process_state
    (tdef[0], state, cls, err))
ValueError: uncompilable regex "'''" in state 'tsqs' of <class 'pygments.lexers.python.PythonLexer'>: maximum recursion depth exceeded in cmp

Original exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 845, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 619, in _get_data
    data = getter(row_id, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_annot_funcs.py", line 1783, in get_annot_quality_texts
    quality_list = ibs.get_annot_qualities(aid_list)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_annot_funcs.py", line 1752, in get_annot_qualities
    const.ANNOTATION_TABLE, colnames, id_iter, id_colname='rowid', eager=eager)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 449, in get
    return db.get_where(tblname, colnames, params_iter, where_clause, eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 420, in get_where
    eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 560, in _executemany_operation_fmt
    auto_commit=True, eager=eager, **kwargs)
RuntimeError: maximum recursion depth exceeded while calling a Python object

+------

<!!! EXCEPTION !!!>
[!_get_data] problem getting in column 2
<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded
</!!! EXCEPTION !!!>

L______

Error in APIThumbDelegate

+------

<!!! EXCEPTION !!!>
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_thumb_delegate.py", line 314, in sizeHint
    thumb_path = dgt.get_thumb_path_if_exists(view, offset, qtindex)
  File "/home/joncrall/code/guitool/guitool/api_thumb_delegate.py", line 201, in get_thumb_path_if_exists
    data = dgt.get_model_data(qtindex)
  File "/home/joncrall/code/guitool/guitool/api_thumb_delegate.py", line 172, in get_model_data
    data = model.data(qtindex, QtCore.Qt.DisplayRole, **datakw)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 840, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 619, in _get_data
    data = getter(row_id, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_chip_funcs.py", line 260, in get_annot_chip_thumbtup
    thumb_gpaths = ibs.get_annot_chip_thumbpath(aid_list, thumbsize=thumbsize,
  File "/home/joncrall/code/ibeis/ibeis/control/manual_chip_funcs.py", line 221, in get_annot_chip_thumbpath
    annot_uuid_list = ibs.get_annot_visual_uuids(aid_list)
  File "/home/joncrall/code/utool/utool/util_decor.py", line 90, in wrp_noexectb
    raise exc_type, exc_value, exc_traceback
RuntimeError: maximum recursion depth exceeded

[!sizeHint] Error in APIThumbDelegate
<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded
</!!! EXCEPTION !!!>

L______


+------

<!!! EXCEPTION !!!>
[!_get_data] problem getting in column 5
<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded in __instancecheck__
</!!! EXCEPTION !!!>

L______

Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 111, in myexcepthook
    formatted_text = highlight(tbtext, lexer, formatter)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 86, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 66, in format
    formatter.format(tokens, realoutfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 100, in format
    return Formatter.format(self, tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 136, in format_unencoded
    for ttype, value in tokensource:
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 192, in streamer
    for i, t, v in self.get_tokens_unprocessed(text):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 635, in get_tokens_unprocessed
    for item in action(self, m):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 324, in callback
    data), ctx):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 380, in callback
    lx = _other(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 581, in __call__
    cls._tokens = cls.process_tokendef('', cls.get_tokendefs())
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 520, in process_tokendef
    cls._process_state(tokendefs, processed, state)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 484, in _process_state
    str(tdef)))
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 502, in _process_state
    (tdef[0], state, cls, err))
ValueError: uncompilable regex '%(\\(\\w+\\))?[-#0 +]*([0-9]+|[*])?(\\.([0-9]+|[*]))?[hlL]?[diouxXeEfFgGcrs%]' in state 'strings' of <class 'pygments.lexers.python.PythonLexer'>: maximum recursion depth exceeded

Original exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 845, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 619, in _get_data
    data = getter(row_id, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_annot_funcs.py", line 1799, in get_annot_yaw_texts
    yaw_list = ibs.get_annot_yaws(aid_list)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_annot_funcs.py", line 993, in get_annot_yaws
    yaw_list = ibs.db.get(const.ANNOTATION_TABLE, (ANNOT_YAW,), aid_list)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 449, in get
    return db.get_where(tblname, colnames, params_iter, where_clause, eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 420, in get_where
    eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 560, in _executemany_operation_fmt
    auto_commit=True, eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 970, in executemany
    if isinstance(params_iter, (list, tuple)):
RuntimeError: maximum recursion depth exceeded in __instancecheck__

+------

<!!! EXCEPTION !!!>
[!_get_data] problem getting in column 6
<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded in __instancecheck__
</!!! EXCEPTION !!!>

L______

Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 111, in myexcepthook
    formatted_text = highlight(tbtext, lexer, formatter)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 86, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 66, in format
    formatter.format(tokens, realoutfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 100, in format
    return Formatter.format(self, tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 136, in format_unencoded
    for ttype, value in tokensource:
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 192, in streamer
    for i, t, v in self.get_tokens_unprocessed(text):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 635, in get_tokens_unprocessed
    for item in action(self, m):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 324, in callback
    data), ctx):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 380, in callback
    lx = _other(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 581, in __call__
    cls._tokens = cls.process_tokendef('', cls.get_tokendefs())
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 520, in process_tokendef
    cls._process_state(tokendefs, processed, state)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 484, in _process_state
    str(tdef)))
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 502, in _process_state
    (tdef[0], state, cls, err))
ValueError: uncompilable regex '%(\\(\\w+\\))?[-#0 +]*([0-9]+|[*])?(\\.([0-9]+|[*]))?[hlL]?[diouxXeEfFgGcrs%]' in state 'strings' of <class 'pygments.lexers.python.PythonLexer'>: maximum recursion depth exceeded

Original exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 845, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 619, in _get_data
    data = getter(row_id, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_annot_funcs.py", line 1783, in get_annot_quality_texts
    quality_list = ibs.get_annot_qualities(aid_list)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_annot_funcs.py", line 1752, in get_annot_qualities
    const.ANNOTATION_TABLE, colnames, id_iter, id_colname='rowid', eager=eager)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 449, in get
    return db.get_where(tblname, colnames, params_iter, where_clause, eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 420, in get_where
    eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 560, in _executemany_operation_fmt
    auto_commit=True, eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 970, in executemany
    if isinstance(params_iter, (list, tuple)):
RuntimeError: maximum recursion depth exceeded in __instancecheck__

+------

<!!! EXCEPTION !!!>
[!_get_data] problem getting in column 2
<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded while calling a Python object
</!!! EXCEPTION !!!>

L______

Error in APIThumbDelegate

+------

<!!! EXCEPTION !!!>
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_thumb_delegate.py", line 314, in sizeHint
    thumb_path = dgt.get_thumb_path_if_exists(view, offset, qtindex)
  File "/home/joncrall/code/guitool/guitool/api_thumb_delegate.py", line 201, in get_thumb_path_if_exists
    data = dgt.get_model_data(qtindex)
  File "/home/joncrall/code/guitool/guitool/api_thumb_delegate.py", line 172, in get_model_data
    data = model.data(qtindex, QtCore.Qt.DisplayRole, **datakw)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 840, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 619, in _get_data
    data = getter(row_id, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_chip_funcs.py", line 260, in get_annot_chip_thumbtup
    thumb_gpaths = ibs.get_annot_chip_thumbpath(aid_list, thumbsize=thumbsize,
  File "/home/joncrall/code/ibeis/ibeis/control/manual_chip_funcs.py", line 221, in get_annot_chip_thumbpath
    annot_uuid_list = ibs.get_annot_visual_uuids(aid_list)
  File "/home/joncrall/code/utool/utool/util_decor.py", line 90, in wrp_noexectb
    raise exc_type, exc_value, exc_traceback
RuntimeError: maximum recursion depth exceeded while calling a Python object

[!sizeHint] Error in APIThumbDelegate
<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded while calling a Python object
</!!! EXCEPTION !!!>

L______


+------

<!!! EXCEPTION !!!>
[!_get_data] problem getting in column 5
<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded
</!!! EXCEPTION !!!>

L______

Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 111, in myexcepthook
    formatted_text = highlight(tbtext, lexer, formatter)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 86, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 66, in format
    formatter.format(tokens, realoutfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 100, in format
    return Formatter.format(self, tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 136, in format_unencoded
    for ttype, value in tokensource:
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 192, in streamer
    for i, t, v in self.get_tokens_unprocessed(text):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 635, in get_tokens_unprocessed
    for item in action(self, m):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 324, in callback
    data), ctx):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 380, in callback
    lx = _other(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 581, in __call__
    cls._tokens = cls.process_tokendef('', cls.get_tokendefs())
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 520, in process_tokendef
    cls._process_state(tokendefs, processed, state)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 484, in _process_state
    str(tdef)))
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 502, in _process_state
    (tdef[0], state, cls, err))
ValueError: uncompilable regex '%(\\(\\w+\\))?[-#0 +]*([0-9]+|[*])?(\\.([0-9]+|[*]))?[hlL]?[diouxXeEfFgGcrs%]' in state 'strings' of <class 'pygments.lexers.python.PythonLexer'>: maximum recursion depth exceeded

Original exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 845, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 619, in _get_data
    data = getter(row_id, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_annot_funcs.py", line 1799, in get_annot_yaw_texts
    yaw_list = ibs.get_annot_yaws(aid_list)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_annot_funcs.py", line 993, in get_annot_yaws
    yaw_list = ibs.db.get(const.ANNOTATION_TABLE, (ANNOT_YAW,), aid_list)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 449, in get
    return db.get_where(tblname, colnames, params_iter, where_clause, eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 420, in get_where
    eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 560, in _executemany_operation_fmt
    auto_commit=True, eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 994, in executemany
    with SQLExecutionContext(db, operation, **contextkw) as context:
  File "/home/joncrall/code/ibeis/ibeis/control/_sql_helpers.py", line 315, in __init__
    context.operation_type = get_operation_type(operation)  # Parse the optype
RuntimeError: maximum recursion depth exceeded

+------

<!!! EXCEPTION !!!>
[!_get_data] problem getting in column 6
<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded
</!!! EXCEPTION !!!>

L______

Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 111, in myexcepthook
    formatted_text = highlight(tbtext, lexer, formatter)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 86, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/__init__.py", line 66, in format
    formatter.format(tokens, realoutfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 100, in format
    return Formatter.format(self, tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/usr/local/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 136, in format_unencoded
    for ttype, value in tokensource:
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 192, in streamer
    for i, t, v in self.get_tokens_unprocessed(text):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 635, in get_tokens_unprocessed
    for item in action(self, m):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 324, in callback
    data), ctx):
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 380, in callback
    lx = _other(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 581, in __call__
    cls._tokens = cls.process_tokendef('', cls.get_tokendefs())
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 520, in process_tokendef
    cls._process_state(tokendefs, processed, state)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 484, in _process_state
    str(tdef)))
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 502, in _process_state
    (tdef[0], state, cls, err))
ValueError: uncompilable regex '%(\\(\\w+\\))?[-#0 +]*([0-9]+|[*])?(\\.([0-9]+|[*]))?[hlL]?[diouxXeEfFgGcrs%]' in state 'strings' of <class 'pygments.lexers.python.PythonLexer'>: maximum recursion depth exceeded

Original exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 845, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 619, in _get_data
    data = getter(row_id, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_annot_funcs.py", line 1783, in get_annot_quality_texts
    quality_list = ibs.get_annot_qualities(aid_list)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_annot_funcs.py", line 1752, in get_annot_qualities
    const.ANNOTATION_TABLE, colnames, id_iter, id_colname='rowid', eager=eager)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 449, in get
    return db.get_where(tblname, colnames, params_iter, where_clause, eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 420, in get_where
    eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 560, in _executemany_operation_fmt
    auto_commit=True, eager=eager, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 994, in executemany
    with SQLExecutionContext(db, operation, **contextkw) as context:
  File "/home/joncrall/code/ibeis/ibeis/control/_sql_helpers.py", line 315, in __init__
    context.operation_type = get_operation_type(operation)  # Parse the optype
RuntimeError: maximum recursion depth exceeded

+------

<!!! EXCEPTION !!!>
[!_get_data] problem getting in column 2
<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded while calling a Python object
</!!! EXCEPTION !!!>

L______

Error in APIThumbDelegate

+------

<!!! EXCEPTION !!!>
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_thumb_delegate.py", line 314, in sizeHint
    thumb_path = dgt.get_thumb_path_if_exists(view, offset, qtindex)
  File "/home/joncrall/code/guitool/guitool/api_thumb_delegate.py", line 201, in get_thumb_path_if_exists
    data = dgt.get_model_data(qtindex)
  File "/home/joncrall/code/guitool/guitool/api_thumb_delegate.py", line 172, in get_model_data
    data = model.data(qtindex, QtCore.Qt.DisplayRole, **datakw)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 840, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 619, in _get_data
    data = getter(row_id, **kwargs)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_chip_funcs.py", line 260, in get_annot_chip_thumbtup
    thumb_gpaths = ibs.get_annot_chip_thumbpath(aid_list, thumbsize=thumbsize,
  File "/home/joncrall/code/ibeis/ibeis/control/manual_chip_funcs.py", line 221, in get_annot_chip_thumbpath
    annot_uuid_list = ibs.get_annot_visual_uuids(aid_list)
  File "/home/joncrall/code/ibeis/ibeis/control/manual_annot_funcs.py", line 943, in get_annot_visual_uuids
    const.ANNOTATION_TABLE, colnames, id_iter, id_colname='rowid')
  File "/home/joncrall/code/ibeis/ibeis/control/SQLDatabaseControl.py", line 449, in get
    return db.get_where(tblname, colnames, params_iter, where_clause, eager=eager, **kwargs)
RuntimeError: maximum recursion depth exceeded while calling a Python object

[!sizeHint] Error in APIThumbDelegate
<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded while calling a Python object
</!!! EXCEPTION !!!>

L______
L______

Original exception was:
Traceback (most recent call last):
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 813, in data
    data = model._get_data(qtindex, **kwargs)
  File "/home/joncrall/code/guitool/guitool/api_item_model.py", line 621, in _get_data
    utool.printex(ex, 'problem getting in column %r' % (col,))
  File "/home/joncrall/code/utool/utool/util_dbg.py", line 887, in printex
    print_func('\n+------\n')
  File "/home/joncrall/code/utool/utool/util_inject.py", line 144, in print
    util_logging.__UTOOL_PRINT__(*args)
  File "/home/joncrall/code/utool/utool/util_logging.py", line 225, in utool_print
    return  __UTOOL_ROOT_LOGGER__.info(', '.join(map(str, args)))
  File "/usr/lib/python2.7/logging/__init__.py", line 1152, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1270, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/logging/__init__.py", line 1244, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
  File "/usr/lib/python2.7/logging/__init__.py", line 266, in __init__
    self.levelname = getLevelName(level)
RuntimeError: maximum recursion depth exceeded
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/joncrall/code/utool/utool/util_inject.py", line 109, in myexcepthook
    lexer = get_lexer_by_name('pytb', stripall=True)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 87, in get_lexer_by_name
    _load_lexers(module_name)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 41, in _load_lexers
    mod = __import__(module_name, None, None, ['__all__'])
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/python.py", line 14, in <module>
    from pygments.lexer import Lexer, RegexLexer, include, bygroups, using, \
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 24, in <module>
    from pygments.regexopt import regex_opt
  File "/usr/local/lib/python2.7/dist-packages/pygments/regexopt.py", line 19, in <module>
    CS_ESCAPE = re.compile(r'[\^\\\-\]]')
  File "/usr/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 242, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python2.7/sre_compile.py", line 498, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python2.7/sre_parse.py", line 678, in parse
    source = Tokenizer(str)
  File "/usr/lib/python2.7/sre_parse.py", line 181, in __init__
    self.__next()
RuntimeError: maximum recursion depth exceeded

"""

